### ISSUE TITLE
Choice Proposal

### ISSUE THREAD

**Issue by AldaronLau** [muon-data/muon#3]
This would include Rust-style enums (or C-Style union + tag):

```muon
:::
character: choice
  Person: list text
  Animal: text
  Spirit: int
:::
character:
  Person: multiple text
character:
  Animal: fox
character:
  Spirit: 5
```

For C-Style enums, an type in schema can be omitted and shortcut could be used:

```muon
:::
switch_a: choice Direction
  Forward
  Neutral
  Backward
switch_b: choice Direction
:::
switch_a: Neutral
switch_b: Forward
```

You can also mix variants with associated data with ones that don't have any:
```muon
:::
thing: list choice
  None
  Red: record
    value: int
    name: text
  Blue: int
  Nothing
:::
thing: None
thing:
  Red: 10
    name: Bright
thing: Nothing
thing:
  Blue: 25
```

@DougLau thoughts?

**edit**: Rename `union` to `choice`, add mixed associated data and without associated data example.

**Comment by DougLau** [comment]
See https://github.com/muon-data/muon/commit/f5a9378a7dde12a16b08c3d59559ad2cbd90cbd1

**Comment by AldaronLau** [comment]
☺
